services:
  db:
    image: mysql:8.0
    container_name: demo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: demo_app
    restart: always
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPLUGIN_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_CONFIG_EXTRA: |
        define('CHAT_NODE_SERVER_URL', 'http://chat-server:3000');
        define('CHAT_WS_URL', 'ws://localhost:8080');
    volumes:
      - ./wp-content:/var/www/html/wp-content

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: wpuser
      PMA_PASSWORD: wppass
    depends_on:
      - db

  chat-server:
    build:
      context: ./chat-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - WP_URL=http://wordpress:80
    restart: unless-stopped

volumes:
  db_data: {}